# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=350)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('article_date', models.DateField()),
                ('article_time', models.CharField(max_length=5)),
                ('latitude', models.IntegerField(blank=True)),
                ('longitude', models.IntegerField(blank=True)),
                ('region', models.CharField(blank=True, choices=[('city', 'city'), ('region', 'region')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='scraping.Category'),
        ),
    ]
